from xml.dom import minidom
p_doc = minidom.Document()
savepath = "/home/monkiki/PycharmProjects/measurement_project/stereo_vision/static/global_info.xml"
root = p_doc.createElement('global_info')
## root
p_doc.appendChild(root)
## time of calibration
A_calibration_time = p_doc.createElement('A_calibration_time')
A_calibration_time.appendChild(p_doc.createElement('time'))
root.appendChild(A_calibration_time)

B_calibration_time = p_doc.createElement('B_calibration_time')
B_calibration_time.appendChild(p_doc.createElement('time'))
root.appendChild(B_calibration_time)

## time of global
global_time = p_doc.createElement('global_time')
global_time.appendChild(p_doc.createElement('time'))
root.appendChild(global_time)
## origin coordi
origin = p_doc.createElement('origin')
AP1 = p_doc.createElement('AP1')
AP2 = p_doc.createElement('AP2')
AP3 = p_doc.createElement('AP3')
BP1 = p_doc.createElement('BP1')
BP2 = p_doc.createElement('BP2')
BP3 = p_doc.createElement('BP3')
root.appendChild(origin)
origin.appendChild(AP1)
origin.appendChild(AP2)
origin.appendChild(AP3)
origin.appendChild(BP1)
origin.appendChild(BP2)
origin.appendChild(BP3)
## T2A coordi
T2A = p_doc.createElement('T2A')
APO = p_doc.createElement('APO')
APH = p_doc.createElement('APH')
APW = p_doc.createElement('APW')
BPO = p_doc.createElement('BPO')
BPH = p_doc.createElement('BPH')
BPW = p_doc.createElement('BPW')
R_T2A = p_doc.createElement('R_T2A')
T_T2A = p_doc.createElement('T_T2A')
root.appendChild(T2A)
T2A.appendChild(APO)
T2A.appendChild(APH)
T2A.appendChild(APW)
T2A.appendChild(BPO)
T2A.appendChild(BPH)
T2A.appendChild(BPW)
T2A.appendChild(R_T2A)
T2A.appendChild(T_T2A)
## S2S coordi
S2S = p_doc.createElement('S2S')
APOs = p_doc.createElement('APOs')
APHs = p_doc.createElement('APHs')
APWs = p_doc.createElement('APWs')
BPOs = p_doc.createElement('BPOs')
BPHs = p_doc.createElement('BPHs')
BPWs = p_doc.createElement('BPWs')
T_AS2S = p_doc.createElement('T_AS2S')
T_BS2S = p_doc.createElement('T_BS2S')
root.appendChild(S2S)
S2S.appendChild(APOs)
S2S.appendChild(APHs)
S2S.appendChild(APWs)
S2S.appendChild(BPOs)
S2S.appendChild(BPHs)
S2S.appendChild(BPWs)
S2S.appendChild(T_AS2S)
S2S.appendChild(T_BS2S)



fp = open(savepath,'w')
p_doc.writexml(fp, indent='\t', addindent='\t', newl='\n', encoding="utf-8")
